### ISSUE TITLE
Build and Archive error

### ISSUE THREAD

**Issue by munkhorgil** [google/gtm-session-fetcher#103]
When I build from xcodeproject I got following error:
```
ld: library not found for -lGTMSessionFetcher
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
It works fine in xworkspace, Unfortunately I can not Archive it says **The operation could not complete no file or directory**

**React Native - Firebase**

**Comment by thomasvl** [comment]
This is likely going to be specific to however your builds are set up.

Workspaces have a setting for finding implicit dependencies between projects, it sounds like your projects are taking advantage of that, so when not opening things with the workspace, that cross project dependency isn't found.

What ever guide/setup you used for your set likely will be what you need to check for how to resolve this.  If you are using CocoaPods, I believe they say you always need to use the workspace and not the projects directly.

**Comment by munkhorgil** [comment]
@thomasvl Yep, It builds fine in workspace even so I can't archive it above error occurse, I suspect that related to this issue even it is working fine workspace. Don't you think so?
