### ISSUE TITLE
warning: block implicitly retains 'self

### ISSUE THREAD

**Issue by paulb777** [google/gtm-session-fetcher#110]
- WARN  | [Firebase/Auth, Firebase/Invites, Firebase/Performance, and more...] xcodebuild:  GTMSessionFetcher/Source/GTMSessionFetcher.m:943:9: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior [-Wimplicit-retain-self]
    - WARN  | [Firebase/Auth, Firebase/Invites, Firebase/Performance, and more...] xcodebuild:  GTMSessionFetcher/Source/GTMSessionFetcher.m:944:9: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior [-Wimplicit-retain-self]
    - WARN  | [Firebase/Auth, Firebase/Invites, Firebase/Performance, and more...] xcodebuild:  GTMSessionFetcher/Source/GTMSessionFetcher.m:945:10: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior [-Wimplicit-retain-self]
    - WARN  | [Firebase/Auth, Firebase/Invites, Firebase/Performance, and more...] xcodebuild:  GTMSessionFetcher/Source/GTMSessionFetcher.m:975:11: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior [-Wimplicit-retain-self]
    - WARN  | [Firebase/Auth, Firebase/Invites, Firebase/Performance, and more...] xcodebuild:  GTMSessionFetcher/Source/GTMSessionFetcher.m:988:63: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior [-Wimplicit-retain-self]
    - WARN  | [Firebase/Auth, Firebase/Invites, Firebase/Performance, and more...] xcodebuild:  GTMSessionFetcher/Source/GTMSessionFetcher.m:1041:60: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior [-Wimplicit-retain-self]
    - WARN  | [Firebase/Auth, Firebase/Invites, Firebase/Performance, and more...] xcodebuild:  GTMSessionFetcher/Source/GTMSessionFetcher.m:1056:13: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior [-Wimplicit-retain-self]
    - WARN  | [Firebase/Auth, Firebase/Invites, Firebase/Performance, and more...] xcodebuild:  GTMSessionFetcher/Source/GTMSessionFetcher.m:1057:31: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior [-Wimplicit-retain-self]
    - WARN  | [Firebase/Auth, Firebase/Invites, Firebase/Performance, and more...] xcodebuild:  GTMSessionFetcher/Source/GTMSessionFetcher.m:1074:11: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior [-Wimplicit-retain-self]
    - WARN  | [Firebase/Auth, Firebase/Invites, Firebase/Performance, and more...] xcodebuild:  GTMSessionFetcher/Source/GTMSessionFetcher.m:1825:40: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior [-Wimplicit-retain-self]
    - WARN  | [Firebase/Auth, Firebase/Invites, Firebase/Performance, and more...] xcodebuild:  GTMSessionFetcher/Source/GTMSessionFetcher.m:2118:32: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior [-Wimplicit-retain-self]
    - WARN  | [Firebase/Auth, Firebase/Invites, Firebase/Performance, and more...] xcodebuild:  GTMSessionFetcher/Source/GTMSessionFetcher.m:2120:10: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior [-Wimplicit-retain-self]
    - WARN  | [Firebase/Auth, Firebase/Invites, Firebase/Performance, and more...] xcodebuild:  GTMSessionFetcher/Source/GTMSessionFetcher.m:2121:9: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior [-Wimplicit-retain-self]
    - WARN  | [Firebase/Auth, Firebase/Invites, Firebase/Performance, and more...] xcodebuild:  GTMSessionFetcher/Source/GTMSessionFetcher.m:2125:66: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior [-Wimplicit-retain-self]
    - WARN  | [Firebase/Auth, Firebase/Invites, Firebase/Performance, and more...] xcodebuild:  GTMSessionFetcher/Source/GTMSessionFetcher.m:2356:44: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior [-Wimplicit-retain-self]
    - WARN  | [Firebase/Auth, Firebase/Invites, Firebase/Performance, and more...] xcodebuild:  GTMSessionFetcher/Source/GTMSessionFetcher.m:2362:17: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior [-Wimplicit-retain-self]
    - WARN  | [Firebase/Auth, Firebase/Invites, Firebase/Performance, and more...] xcodebuild:  GTMSessionFetcher/Source/GTMSessionFetcher.m:2372:21: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior [-Wimplicit-retain-self]
    - WARN  | [Firebase/Auth, Firebase/Invites, Firebase/Performance, and more...] xcodebuild:  GTMSessionFetcher/Source/GTMSessionFetcher.m:2488:25: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior [-Wimplicit-retain-self]
    - WARN  | [Firebase/Auth, Firebase/Invites, Firebase/Performance, and more...] xcodebuild:  GTMSessionFetcher/Source/GTMSessionFetcher.m:2542:31: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior [-Wimplicit-retain-self]
    - WARN  | [Firebase/Auth, Firebase/Invites, Firebase/Performance, and more...] xcodebuild:  GTMSessionFetcher/Source/GTMSessionFetcher.m:2545:52: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior [-Wimplicit-retain-self]
    - WARN  | [Firebase/Auth, Firebase/Invites, Firebase/Performance, and more...] xcodebuild:  GTMSessionFetcher/Source/GTMSessionFetcher.m:2606:25: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior [-Wimplicit-retain-self]
    - WARN  | [Firebase/Auth, Firebase/Invites, Firebase/Performance, and more...] xcodebuild:  GTMSessionFetcher/Source/GTMSessionUploadFetcher.m:1169:9: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior [-Wimplicit-retain-self]
    - WARN  | [Firebase/Auth, Firebase/Invites, Firebase/Performance, and more...] xcodebuild:  GTMSessionFetcher/Source/GTMSessionUploadFetcher.m:1216:13: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior [-Wimplicit-retain-self]
    - WARN  | [Firebase/Auth, Firebase/Invites, Firebase/Performance, and more...] xcodebuild:  GTMSessionFetcher/Source/GTMSessionUploadFetcher.m:1639:13: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior [-Wimplicit-retain-self]

**Comment by thomasvl** [comment]
Reports like this aren't overly useful with more info - What Xcode version(s)?  Any custom setting added?  Repo steps, etc.

**Comment by paulb777** [comment]
Sorry. I thought the warning might have been explicit enough. They're warnings from `pod spec lint` on pods that depend on GTMSessionFetcher.  They're perhaps triggered by Xcode 9 and/or recent updates from the latest Xcodebuild gem used by CocoaPods. I'll work on a repro in the next few hours.

**Comment by thomasvl** [comment]
We didn't get any warnings when we push the 1.1.13 spec earlier this month.

**Comment by thomasvl** [comment]
Hm, was that not released as a updated dep yet?

```
$ gem list Xcodeproj

*** LOCAL GEMS ***

xcodeproj (1.5.4)
$ gem install cocoapods
Successfully installed cocoapods-1.4.0
Parsing documentation for cocoapods-1.4.0
Done installing documentation for cocoapods after 2 seconds
1 gem installed
$ gem list Xcodeproj

*** LOCAL GEMS ***

xcodeproj (1.5.4)
```

https://guides.cocoapods.org/using/getting-started.html#updating-cocoapods documents `gem install cocoapods` as all that one needs to do to update?

**Comment by paulb777** [comment]
CocoaPods/CocoaPods has not yet released an updated dep to Xcodeproj, but many users are forcing the Xcodeproj update to work with Xcode 9.3 and other issues addressed by xcodeproj 1.5.6.

**Comment by thomasvl** [comment]
`gem update` got me the update and a pile of others (including atleast one thing that failed), but that does seem to show the error now.  Will look.

**Comment by thomasvl** [comment]
fyi - I'm not going to do a pods push at the moment, just incase something else comes up.

**Comment by kaydee98** [comment]
do you have an ETA for making this push?

**Comment by erfe1** [comment]
هل تم الدفع

**Comment by thomasvl** [comment]
@kaydee98 just did a 1.1.14 release and did the pod push also.
