### ISSUE TITLE
OS_dispatch_semaphore Memory Leak.

### ISSUE THREAD

**Issue by MussaCharles** [google/gtm-session-fetcher#112]
I am using firebase and I think gtm-session-fetcher was installed during firebase products installation. I am debugging my app for memory leaks and found out that "OS_dispatch_semaphore" which happened to be in gmt-session-fetcher file is causing the leak. Is there any solution or suggestion on how to solve this issue?

**Comment by thomasvl** [comment]
It should get released when the `GTMSessionFetcherService` that owns it gets released.  Is there a Service not getting released also?

**Comment by MussaCharles** [comment]
Hi, sorry for the late reply. The only memory issue was marked on "OS_dispatch_semaphore", I am using Xcode graph to debug so I couldn't see any other service not being released.

**Comment by thomasvl** [comment]
If you can make a small repro case, someone else might be able to help figure it out.  Looking at the `GTMSessionFetcherService` code, ARC should be properly managing retains on it.

**Comment by MussaCharles** [comment]
I forgot to close this, the issue was resolved after updating some of the pods.
