### ISSUE TITLE
XCode 9.3 warnings for GTMSessionFetcher 1.1.14

### ISSUE THREAD

**Issue by TedHopp** [google/gtm-session-fetcher#115]
I'm seeing the following warnings when I build my project:

> /Users/tedhopp/Public/Projects/My Tikkun/Pods/GTMSessionFetcher/Source/GTMMIMEDocument.m:396:47: Format specifies type 'ssize_t' (aka 'long') but the argument has type 'int'  
> /Users/tedhopp/Public/Projects/My Tikkun/Pods/GTMSessionFetcher/Source/GTMMIMEDocument.m:396:64: Values of type 'NSInteger' should not be used as format arguments; add an explicit cast to 'long' instead  
> /Users/tedhopp/Public/Projects/My Tikkun/Pods/GTMSessionFetcher/Source/GTMMIMEDocument.m:434:66: Format specifies type 'ssize_t' (aka 'long') but the argument has type 'int'  
> /Users/tedhopp/Public/Projects/My Tikkun/Pods/GTMSessionFetcher/Source/GTMSessionFetcher.m:434:48: Values of type 'NSInteger' should not be used as format arguments; add an explicit cast to 'long' instead  
> /Users/tedhopp/Public/Projects/My Tikkun/Pods/GTMSessionFetcher/Source/GTMSessionFetcher.h:301:69: Expanded from macro 'GTMSESSION_ASSERT_DEBUG'  
> /Users/tedhopp/Public/Projects/My Tikkun/Pods/GTMSessionFetcher/Source/GTMSessionFetcher.m:2663:28: Values of type 'NSInteger' should not be used as format arguments; add an explicit cast to 'long' instead  
> /Users/tedhopp/Public/Projects/My Tikkun/Pods/GTMSessionFetcher/Source/GTMSessionFetcher.h:284:45: Expanded from macro 'GTMSESSION_LOG_DEBUG'

I'm using XCode 9.3 and GTMSessionFetcher version 1.1.14.

**Comment by crisp** [comment]
I'm seeing this also... is anyone looking at this? Thanks!

**Comment by thomasvl** [comment]
See the line right about your comment (reference in a PR)  😄

**Comment by crisp** [comment]
Excellent. Thanks!

**Comment by crisp** [comment]
@thomasvl Is there a plan to update this project to pick up the update to this in its dependencies?: https://github.com/google/gtm-oauth2

**Comment by thomasvl** [comment]
fyi - gtm-oauth2 is [deprecated](https://github.com/google/gtm-oauth2#warning-deprecation-notice)

If you are getting it via pods, it should just "show up" when you update your pods.  If you are using raw source, go ahead and send a PR to update the submodule reference if you want the master one updated also.

**Comment by crisp** [comment]
ok. Thanks
