### ISSUE TITLE
Argument to 'NSString' method 'caseInsensitiveCompare:' cannot be nil

### ISSUE THREAD

**Issue by Idomo** [google/gtm-session-fetcher#136]
![image](https://user-images.githubusercontent.com/26777129/48871319-eda6da80-edec-11e8-93be-af95dff410b6.png)
On `line 2281`.

Please check for fix,
Ido.

**Comment by thomasvl** [comment]
Can you please provide more info?  How are you building, what settings, what version of Xcode, etc. So we can figure out what conditions this is triggering.  It might happen in your setup but not in someone else's.

**Comment by Idomo** [comment]
It showing when you run Editor -> Analyze on xCode 10.1.
