### ISSUE TITLE
`GTMSessionUploadFetcher` endlessly sends empty chunks when `uploadFileURL` points to an empty or non-existing file

### ISSUE THREAD

**Issue by maksymmalyhin** [google/gtm-session-fetcher#140]
Issues like [this](https://github.com/firebase/firebase-ios-sdk/issues/2350) is an implication of this issue.

**Comment by thomasvl** [comment]
What is _#2350_?  This project doesn't have an issue with that number.

**Comment by maksymmalyhin** [comment]
@thomasvl Ah, sorry, I need to add a global link, since it is an issue from another project: https://github.com/firebase/firebase-ios-sdk/issues/2350

**Comment by maksymmalyhin** [comment]
@thomasvl I think, I can provide a fix for the issue. Would you mind me doing that?

**Comment by thomasvl** [comment]
> @thomasvl I think, I can provide a fix for the issue. Would you mind me doing that?

Nope, go for it!

**Comment by thomasvl** [comment]
I believe that PR fixed this.
