### ISSUE TITLE
Mac Catalyst Support

### ISSUE THREAD

**Issue by JonasGessner** [google/gtm-session-fetcher#156]
This library is using a number of APIs that are deprecated and that are unavailable on mac catalyst. Adding calls to newer APIs and appropriate availability checks and preprocessor checks to know when to use the newer APIs would allow supporting Catalyst, which would be nice!

Here are the errors:

<img width="411" src="https://user-images.githubusercontent.com/1156152/66708324-1a3e4a80-ed4f-11e9-9294-e791146ce8bb.png">

<img width="533" src="https://user-images.githubusercontent.com/1156152/66776145-08cb7e80-eec6-11e9-9912-65815d1c9087.png">

**Comment by appfrilans** [comment]
Also interested in this! Some features in my project are on hold waiting for this one.

**Comment by thomasvl** [comment]
The issue flagged here is likely fixed via #155, can either of your confirm?

We'll likely need to cut a release to make it easier to use, but I'd like to confirm it before doing so.

**Comment by JonasGessner** [comment]
It would partially fix it. `SecTrustEvaluate` is also deprecated would need to be replaced and all uses of `UIWebView` would need to be removed or replaced with `WKWebView`.

**Comment by thomasvl** [comment]
Since the logview is more of a debugging aid, it might make sense to retire it or atleast get the other parts done first.

**Comment by thomasvl** [comment]
And #155 actually wasn't enough for even that one issue.  Looks like if you set the min to the newest versions, the `else` clause of the `if (@avaiable(…)) …` still triggers the warning/error around the deprecated api, so the code has to be gated via the preprocessor (I thought clang did like swiftc and realize the `else` wouldn't be used and thus suppressed the warnings/errors in there.

**Comment by JonasGessner** [comment]
True, you'd have to do something like [this](https://github.com/JonasGessner/JGProgressHUD/commit/08d130dd614a743f813286f096804c43a6ffa3f6).

**Comment by mwyman** [comment]
The TLS, SecTrustEvaluate, and UIWebView deprecations should all be handled now.

**Comment by JonasGessner** [comment]
Seems to work! Thanks

**Comment by mwyman** [comment]
Excellent! In that case, I'm going to close this issue. If further Catalyst problems crop up, please open a new one.
