### ISSUE TITLE
Segfault when setting TLSMinimumSupportedProtocolVersion

### ISSUE THREAD

**Issue by wvdk** [google/gtm-session-fetcher#176]
Running on iOS 13 I get a segfault when the GTMSessionFetcher sets `_configuration.TLSMinimumSupportedProtocolVersion` to `tls_protocol_version_TLSv12`

```swift
#if !GTM_ALLOW_INSECURE_REQUESTS
#if GTM_SDK_REQUIRES_TLSMINIMUMSUPPORTEDPROTOCOLVERSION
      _configuration.TLSMinimumSupportedProtocolVersion = tls_protocol_version_TLSv12;
#elif GTM_SDK_SUPPORTS_TLSMINIMUMSUPPORTEDPROTOCOLVERSION
      if (@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)) {
        _configuration.TLSMinimumSupportedProtocolVersion = tls_protocol_version_TLSv12;
      } else {
        _configuration.TLSMinimumSupportedProtocol = kTLSProtocol12;
      }
#else
      _configuration.TLSMinimumSupportedProtocol = kTLSProtocol12;
#endif  // GTM_SDK_REQUIRES_TLSMINIMUMSUPPORTEDPROTOCOLVERSION
#endif

```

```
2020-01-08 10:59:13.882012-0800 OctiDev[1713:2662800] -[__NSCFURLSessionConfiguration_Mutable setTLSMinimumSupportedProtocolVersion:]: unrecognized selector sent to instance 0x10cabe450
2020-01-08 10:59:13.882922-0800 OctiDev[1713:2662800] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFURLSessionConfiguration_Mutable setTLSMinimumSupportedProtocolVersion:]: unrecognized selector sent to instance 0x10cabe450'
```

**Comment by thomasvl** [comment]
Any change the device isn't on a GM of iOS 13 (i.e. - this many months later and it is on a beta still)?  Because the app is documented as being in iOS 13 - https://developer.apple.com/documentation/foundation/nsurlsessionconfiguration/3362533-tlsminimumsupportedprotocolversi

**Comment by thomasvl** [comment]
We've worked around this in #170 (doesn't look like we've cut a release since then), but eventually that stopgap will get removed since we shouldn't have to support betas that long after GM.

**Comment by wvdk** [comment]
Was getting the crash on an iPad with what must have been a pre-GM iOS 13.0. Updated to iOS 13.3 and don't get the segfault. Would be great to get that work around in a cocoa pods release of Firebase for the few folks still on the beta. Thanks for the help!

**Comment by mwyman** [comment]
We can spin a release with the fix.

But as Tom mentioned we'll remove that at some future point, since supporting 6+-month-obsolete beta OS versions isn't really something we want to be in the habit of :)

**Comment by mwyman** [comment]
FYI, have pushed the pod spec for v1.3.1.

**Comment by wvdk** [comment]
Thank you 🙏
