### ISSUE TITLE
Using Package Manager Resources in Swift PM Unit Tests

### ISSUE THREAD

**Issue by karimhm** [google/gtm-session-fetcher#192]
Currently, in order to have successful tests when using the Swift Package Manager the **gettysburgaddress.txt** file is copied manually to the unit test bundle resources folder.
https://github.com/google/gtm-session-fetcher/blob/83e8f3c9d9806866fb453296ea888bdc6c3dd7a7/Source/UnitTests/GTMSessionFetcherFetchingTest.m#L94-L126

[Swift 5.3](https://swift.org/blog/5-3-release-process/) introduced a new feature called [Package Manager Resources](https://github.com/apple/swift-evolution/blob/master/proposals/0271-package-manager-resources.md). Once this gets rolled into production, it must be used to copy resources rather than doing it manually.

**Comment by karimhm** [comment]
This happen due to a known bug ([SR-12912](https://bugs.swift.org/browse/SR-12912)). The following PR ([#2905](https://github.com/apple/swift-package-manager/pull/2905)) should solve it

**Comment by thomasvl** [comment]
I also posted on the [Swift Forums](https://forums.swift.org/t/5-3-resources-support-not-working-on-with-swift-test/40381) about this and they also pointed at that PR, but I'm not sure if it is the same problem.  That fix shows the old code path calling `fatalError` if it can't make the `Bundle`, but I'm not crashing, I'm getting back `nil` in the ObjC code.

**Comment by karimhm** [comment]
We should file a new bug then. [XMPPFramework #1177](https://github.com/robbiehanson/XMPPFramework/pull/1177) suffer from the same issue.

**Comment by thomasvl** [comment]
Opened https://bugs.swift.org/browse/SR-13560 also.

**Comment by karimhm** [comment]
@thomasvl One workaround is just recently knew about is to use `xcodebuild` to test Swift packages rather than the `swift` tool. The resources issue ([SR-13560](https://bugs.swift.org/browse/SR-13560)) seem to be present inside `swift` tool only.

Example:
```bash
xcodebuild -scheme GTMSessionFetcher-Package -destination "name=iPhone 11 Pro" test
```
