### ISSUE TITLE
App was killed by system when in background mode

### ISSUE THREAD

**Issue by nguyendinhtrieu1996** [google/gtm-session-fetcher#199]
I start few sections upload files to GG Drive and then I press home button to move application to background mode.
About more than 30 seconds, I launch my app again and It was killed by watchdog.

And I double check in GTMSessionFetcher when it received [backgroundTask exiprationHandler](https://github.com/google/gtm-session-fetcher/blob/48753da9f02bfc29517208d810b6ba7fc67f3344/Source/GTMSessionFetcher.m#L906). If immediately I start new download request or in GTMSessionFetcher call [uploadNextChunk](https://github.com/google/gtm-session-fetcher/blob/48753da9f02bfc29517208d810b6ba7fc67f3344/Source/GTMSessionUploadFetcher.m#L1196) of file. And GTMSessionFetch will create and start new [backgroundTask](https://github.com/google/gtm-session-fetcher/blob/48753da9f02bfc29517208d810b6ba7fc67f3344/Source/GTMSessionFetcher.m#L906). 
So you try to start new backgroundTask after system through bgTask exiprationHandler, watchdog will kill my application

**Comment by mwyman** [comment]
It sounds like you're trying to launch a new background task inside, or after, the background expiration handler has been called, and that's not something supported by the OS and at that point it wouldn't surprise me if the result is the app being killed by the watchdog timer.
