### ISSUE TITLE
Xcode 12 'IPHONEOS_DEPLOYMENT_TARGET' Warning

### ISSUE THREAD

**Issue by muhasturk** [google/gtm-session-fetcher#208]
`The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.1.99`

**Comment by thomasvl** [comment]
I'm guessing you are talking about building under Xcode 12?  The cocoapod is bumped to 9.0 as a minimum for this (#206), but at the moment the checked in Xcode project is still on 8.0 to support older Xcodes there.  Is your issue when specifically opening the Xcode project?

**Comment by thomasvl** [comment]
Actually, we might need to do a release to get the podspec out with the updated minimum.  I'll try to do that today.

**Comment by muhasturk** [comment]
I'm using Xcode Version 12.1 (12A7403)

**Comment by thomasvl** [comment]
Cut a release and pushed cocoapods, so hopefully that takes care of things.
