### ISSUE TITLE
Insecure Storage: Lacking Data Protection

### ISSUE THREAD

**Issue by Shakihassan** [google/gtm-session-fetcher#213]
On line 812 of GTMSessionFetcherLogging.m, the method logFetchWithError:() writes data to a file lacking sufficient encryption settings.The identified method writes data to a file lacking sufficient encryption settings.

**Comment by thomasvl** [comment]
The api is a logging api that has to be enabled by the app.  When logging is enabled, the app is in full control of where things are logged, and can set up any protections needed.
