### ISSUE TITLE
Insecure Transport: Weak SSL Protocol

### ISSUE THREAD

**Issue by Shakihassan** [google/gtm-session-fetcher#214]
The SSLv2, SSLv23, and SSLv3 protocols contain several flaws that make them insecure, so they should not be used to transmit sensitive data.

GTMSessionFetcher.m : 695

**Comment by thomasvl** [comment]
The line reference doesn't make sense, it seems like you are looking at some old code?

Please reopen with read details on how you thing this can happen, the `TLSMinimumSupportedProtocol` on the NSURLSession is set to `kTLSProtocol12`/`tls_protocol_version_TLSv12` to avoid this.
