### ISSUE TITLE
Build error due to missing platforms in the SPM manifest file

### ISSUE THREAD

**Issue by phil1995** [google/gtm-session-fetcher#215]
In https://github.com/google/gtm-session-fetcher/commit/67ba34f8d540029c0c19cd2bf6d092ca9be0527f the supported platforms were removed to remove build warnings. However, in combination with Xcode 12 and for example `GTMAppAuth` or `GoogleAPIClientForRESTCore` this will cause a build error: `The package product 'GTMSessionFetcherCore' requires minimum platform version 9.0 for the iOS platform, but this target supports 8.0`
This is due to the following property of the Swift Package Manager ([Source](https://docs.swift.org/package-manager/PackageDescription/PackageDescription.html)): 

> By default, the Swift Package Manager assigns a predefined minimum deployment version for each supported platforms unless configured using the platforms API. This predefined deployment version will be the oldest deployment target version supported by the installed SDK for a given platform.

Therefore the build error is fixed when the supported platforms are specified again, especially `.iOS(.v8)`. Otherwise you would have to increase the minimum deployment target to `.iOS(.v9)` for every other Swift Package from Google, which has the `GTMSessionFetcher` as dependency.

**Comment by thomasvl** [comment]
Which Xcode version are you using?  Since Xcode 12 doesn't like a minimum of 8 (it issues a warning), it almost seems like the bug should be with SwiftPM, where it shouldn't assume 8 as a minimum since it doesn't accept it without warnings.

**Comment by thomasvl** [comment]
And with other things have a minimum of 8? 67ba34f came from someone on the Firebase team, so we were expecting most things to move up to that minimum.

**Comment by phil1995** [comment]
Xcode Version:  `12.1 (12A7403)`
As mentioned above the `GoogleAPIClientForREST` has as minimum target  [`.iOS(.v8)`](https://github.com/google/google-api-objectivec-client-for-rest/blob/b2a1ef2c38e3a10c053a5e19234b708cd2bbfcb8/Package.swift#L9) and the same applies for [`GTMAppAuth`](https://github.com/google/GTMAppAuth/blob/319b2371c69138665d8cbd7c6700ceccbb49e04f/Package.swift#L26).  Therefore there is a build error as soon as one of the two packages is used.

**Comment by thomasvl** [comment]
Ops, sorry about that.  I meant to trim that section from GTLR when doing the release the other day.  Just did a 1.5.1 release there to update the SwiftPM support to remove the section also to match.

**Comment by phil1995** [comment]
Thanks for the quick update. Could you please do the same for `GTMAppAuth`, as the problem still exists here. Or should I create an issue in the `GTMAppAuth` repository?

**Comment by thomasvl** [comment]
Please file an issue there.  I've helped out in the past there, but other folks run it now.
