### ISSUE TITLE
Crashed: com.google.GTMSessionFetcher.NSURLSessionDelegateQueue (QOS: UNSPECIFIED)

### ISSUE THREAD

**Issue by jenshk** [google/gtm-session-fetcher#216]
I'm getting this crash. It's in the initialization of my app. I suspect it's when it tries to create a Firebase anonymous user. I'm using the 1.5.0 version of the lib.

Any ideas?

Crashed: com.google.GTMSessionFetcher.NSURLSessionDelegateQueue (QOS: UNSPECIFIED)
0  CoreFoundation                 0x188e1535c CFDictionaryGetValue + 88
1  Foundation                     0x18a1c1660 _NSSetLongLongValueAndNotify + 92
2  CFNetwork                      0x1896904c4 _CFNetworkHTTPConnectionCacheSetLimit + 150756
3  Foundation                     0x18a1ea7f4 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 24
4  Foundation                     0x18a0dd120 -[NSBlockOperation main] + 104
5  Foundation                     0x18a1ecbb8 __NSOPERATION_IS_INVOKING_MAIN__ + 24
6  Foundation                     0x18a0dcda8 -[NSOperation start] + 808
7  Foundation                     0x18a1ed624 __NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__ + 24
8  Foundation                     0x18a1ed0d0 __NSOQSchedule_f + 184
9  libdispatch.dylib              0x188ada834 _dispatch_block_async_invoke2 + 148
10 libdispatch.dylib              0x188accac8 _dispatch_client_callout + 20
11 libdispatch.dylib              0x188acfd60 _dispatch_continuation_pop + 416
12 libdispatch.dylib              0x188acf494 _dispatch_async_redirect_invoke + 592
13 libdispatch.dylib              0x188add104 _dispatch_root_queue_drain + 356
14 libdispatch.dylib              0x188add8e8 _dispatch_worker_thread2 + 116
15 libsystem_pthread.dylib        0x1d0dbf8cc _pthread_wqthread + 216
16 libsystem_pthread.dylib        0x1d0dc677c start_wqthread + 8

**Comment by thomasvl** [comment]
While the queue is one the fetcher makes, there really isn't enough to go on here, it is from a block so it could be user supplied code in a completion handler that is actually crashing.

If you can make a more specific repo case that show's it is a the something with the library, we can help take a look, but closing as there isn't something actionable here.
