### ISSUE TITLE
iOS 14.1 App getting terminated in background

### ISSUE THREAD

**Issue by akshatk** [google/gtm-session-fetcher#217]
My app is getting terminated when moved to background and I get the following log on the console:

#### Background task still not ended after expiration handlers were called: <_UIBackgroundTaskInfo: 0x280f75cc0>: taskID = 258, taskName = Called by App, from -[GTMSessionFetcher(GTMSessionUploadFetcherMethods) parentUploadFetcher], creationTime = 194962 (elapsed = 74). This app will likely be terminated by the system. Call UIApplication.endBackgroundTask(_:) to avoid this.

iOS 14.1
GTMSessionFetcher/Core 1.5.0

**Comment by akshatk** [comment]
**Logs:**

Background Task 261 ("Called by XXXX, from -[GTMSessionFetcher(GTMSessionUploadFetcherMethods) parentUploadFetcher]"), was created over 30 seconds ago. In applications running in the background, this creates a risk of termination. Remember to call UIApplication.endBackgroundTask(_:) for your task in a timely manner to avoid this.

Background task still not ended after expiration handlers were called: <_UIBackgroundTaskInfo: 0x2802cddc0>: taskID = 261, taskName = Called by XXXX, from -[GTMSessionFetcher(GTMSessionUploadFetcherMethods) parentUploadFetcher], creationTime = 123280 (elapsed = 42). This app will likely be terminated by the system. Call UIApplication.endBackgroundTask(_:) to avoid this.

**Firebase and GTMSessionFetcher versions:**

Firebase/Analytics (6.27.1)
Firebase/Core (6.27.1)
Firebase/Crashlytics (6.27.1)
GTMSessionFetcher/Core (1.5.0)

**Comment by mwyman** [comment]
Do you have repro steps for this? Also, latest update seems different from the initial issue description, are these two separate issues?

**Comment by akshatk** [comment]
Both are the same issue. Closing this as the problem persisted event after removing GTMSessionFetcher.
