### ISSUE TITLE
+[GTMSessionUploadFetcher load] method takes too much time at app startup

### ISSUE THREAD

**Issue by maksymmalyhin** [google/gtm-session-fetcher#218]
Originally reported in https://github.com/firebase/firebase-ios-sdk/issues/6936.

<img width="2356" alt="Screen Shot 2020-11-10 at 11 09 33" src="https://user-images.githubusercontent.com/8662571/98623284-4fe4a700-2346-11eb-959b-031cf95767ca.png">

Minimal amount or ideally no code should be run in `+[GTMSessionUploadFetcher load]` as it contributes to pre-main app startup time.

**Comment by mwyman** [comment]
Please check that you have not disabled GTMSESSION_RECONNECT_BACKGROUND_SESSIONS_ON_LAUNCH, which moves the background reloading out of `+load` and into an async block after the app launches.

**Comment by maksymmalyhin** [comment]
@mwyman  Sorry for the delayed comment. 

It looks like the user defaults access from `+load` is guarded by the `GTMSESSION_RECONNECT_BACKGROUND_SESSIONS_ON_LAUNCH` in [GTMSessionUploadFetcher](https://github.com/google/gtm-session-fetcher/blob/91ed3d188eb95705fef3c249453b81f32dc557d1/Source/GTMSessionUploadFetcher.m#L152) (in contrast to [GTMSessionFetcher](https://github.com/google/gtm-session-fetcher/blob/91ed3d188eb95705fef3c249453b81f32dc557d1/Source/GTMSessionFetcher.m#L249)
