### ISSUE TITLE
_GTMBridgeAssertValidSelector build failure (GTMSessionFetcher 1.6.0)

### ISSUE THREAD

**Issue by ZOlbrys** [google/gtm-session-fetcher#240]
After updating to `GTMSessionFetcher` 1.6.0 I am seeing the following failure in my build:

```
Undefined symbols for architecture x86_64:
  "_GTMBridgeAssertValidSelector", referenced from:
      -[GTMAppAuthFetcherAuthorization authorizeRequest:delegate:didFinishSelector:] in GTMAppAuth(GTMAppAuthFetcherAuthorization.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Downgrading to 1.5.0 fixes this.

**Comment by thomasvl** [comment]
GTMAppAuth needs to do an updated release that doesn't rely the removed macro.

**Comment by ZOlbrys** [comment]
Thanks for the quick reply - I'll open an issue on GTMAppAuth to convey this.

**Comment by paulb777** [comment]
Isn't this is a breaking change in a minor version update?  Shouldn't the removal wait until a major version?

The GTMAppAuth breakage also causes app's that `pod update` GoogleSignIn` to break as well.

cc: @petea 

![Screen Shot 2021-06-23 at 3 30 11 PM](https://user-images.githubusercontent.com/73870/123176221-e7ab8700-d437-11eb-8681-003798caf12c.png)

```
~/qs/210604/quickstart-ios/authentication (master) $ grep -r GTMBridgeAssertValidSelector *
Pods/GTMSessionFetcher/Source/GTMSessionFetcher.h:    #define GTMBridgeAssertValidSelector GTMSessionFetcherAssertValidSelector
Pods/GTMSessionFetcher/Source/GTMSessionFetcher.h:    #define GTMBridgeAssertValidSelector GTMAssertSelectorNilOrImplementedWithArgs
Pods/GTMAppAuth/GTMAppAuth/Sources/GTMAppAuthFetcherAuthorization.m:#define GTMOAuth2AssertValidSelector GTMBridgeAssertValidSelector
~/qs/210604/quickstart-ios/authentication (master) $ pod update
Update all pods
Updating local specs repositories
Analyzing dependencies
Downloading dependencies
Installing GTMSessionFetcher 1.6.0 (was 1.5.0)
Generating Pods project
Integrating client project
Pod installation complete! There are 6 dependencies from the Podfile and 19 total pods installed.

~/qs/210604/quickstart-ios/authentication (master) $ grep -r GTMBridgeAssertValidSelector *
Pods/GTMAppAuth/GTMAppAuth/Sources/GTMAppAuthFetcherAuthorization.m:#define GTMOAuth2AssertValidSelector GTMBridgeAssertValidSelector
~/qs/210604/quickstart-ios/authentication (master) $
```

**Comment by thomasvl** [comment]
Folks were supposed to stop using it a few years ago, the macro dates back to GTMHTTPFetcher.

**Comment by petea** [comment]
Looks like there's an unreleased fix
<https://github.com/google/GTMAppAuth/commit/50c058439b906cb6cc16915f881517eb5bde70ad>
for this.  I could roll out a GTMAppAuth 1.2.3 release...

**Comment by thomasvl** [comment]
we're also looking at a minor release to bring the old name back.

**Comment by petea** [comment]
On Wed, Jun 23, 2021 at 3:41 PM Thomas Van Lenten
***@***.***> wrote:
> we're also looking at a minor release to bring the old name back.

That would be my preference.

**Comment by thomasvl** [comment]
1.6.1 released, which should fix folks.
