### ISSUE TITLE
Domain=com.google.GTMSessionFetcher Code=-1 

### ISSUE THREAD

**Issue by Keyar** [google/gtm-session-fetcher#28]
With all set correct as per the instructions given here 
https://developers.google.com/identity/toolkit/ios/

I am getting the following error

2016-02-29 22:17:51.552 GitkitDemo[2181:371896] error Error Domain=com.google.GTMSessionFetcher Code=-1 "(null)" UserInfo={NSErrorFailingURLStringKey=(missing URL)}

Anyone got same issue?

**Comment by thomasvl** [comment]
Hard to say with that little of info.  The error makes it sound like an URL was missing from something.  Maybe try the support area for the identity kit since they will be better able to comment on any integration.
