### ISSUE TITLE
Where do I find the built framework after a successful build?

### ISSUE THREAD

**Issue by shankari** [google/gtm-session-fetcher#32]
I'm trying to include gtm-session-fetcher in my project. I am successfully able to get everything to work by copying source over and including it directly in my project, but obviously, it would be better from a modularity perspective to create a framework and include that directly.

So I opened the associated xcodeproj file and built the IOS framework. The build was successful (see below), but I don't see a build directory or a generated framework, either in the source directory or in /Library/Frameworks, which is the install path.

<img width="1138" alt="screen shot 2016-03-05 at 8 07 44 am" src="https://cloud.githubusercontent.com/assets/2423263/13548627/6c3a98b6-e2a9-11e5-93bb-581ae6d4e5b7.png">

<img width="713" alt="screen shot 2016-03-05 at 8 09 31 am" src="https://cloud.githubusercontent.com/assets/2423263/13548634/a3670db0-e2a9-11e5-9d28-49766fc0cbe1.png">

Where should I expect to find the built framework?

**Comment by thomasvl** [comment]
Xcode will put it in your default for built products.

You can make your project reference the project, and directly pick up the framework as product that gets copied into your binary if you want.
