### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by antonydieu** [google/gtm-session-fetcher#33]
google-api-objectivec-client-read-only/Source/HTTPFetcher/GTMHTTPFetcher.m:458:44: 'initWithRequest:delegate:startImmediately:' is deprecated: first deprecated in OS X 10.11 - Use NSURLSession (see NSURLSession.h)

 connection_ = [[connectionClass alloc] initWithRequest:request_
                                                  delegate:self
                                          startImmediately:NO];

i get an error, but i dont fix it? please help me

**Comment by thomasvl** [comment]
I'm a little confused, you're posting about https://github.com/google/gtm-http-fetcher on the session fetcher project.  If your min os version is high enough you should be using the session fetcher (this project).

**Comment by thomasvl** [comment]
Closing this is has gotten spawned in projects also (which seem closer to where you might be getting the real problem)
