### ISSUE TITLE
Critical Severity Risk - Insecure Transport: Weak SSL Protocol

### ISSUE THREAD

**Issue by arunkumar-g3690** [google/gtm-session-fetcher#349]
### Issue Summary
The SSLv2, SSLv23, SSLv3, TLSv1.0, and TLSv1.1 protocols contain flaws that make them insecure and should not be used to transmit sensitive data.

### Explanation
The Transport Layer Security (TLS) and Secure Sockets Layer (SSL) protocols provide a protection mechanism to ensure the authenticity, confidentiality, and integrity of data transmitted between a client and web server. Both TLS and SSL have undergone revisions resulting in periodic version updates. Each new revision is designed to address the security weaknesses discovered in previous versions. Use of an insecure version of TLS/SSL weakens the data protection strength and might allow an attacker to compromise, steal, or modify sensitive information.

Weak versions of TLS/SSL might exhibit one or more of the following properties:

- No protection against man-in-the-middle attacks
- Same key used for authentication and encryption
- Weak message authentication control
- No protection against TCP connection closing
- Use of weak cipher suites

The presence of these properties might allow an attacker to intercept, modify, or tamper with sensitive data.

### Recommendation
Use only the most secure protocols.

Example:
`NSURLSessionConfiguration *configuration = [NSURLSessionConfiguration ephemeralSessionConfiguration];
[configuration setTLSMinimumSupportedProtocol = kTLSProtocol12];
NSURLSession *mySession = [NSURLSession sessionWithConfiguration:configuration delegate:self delegateQueue:operationQueue];`

### Which Version of framework is used?
GoogleSignIn-iOS (7.0.0) uses GTMSessionFetcher (< 4.0, >= 1.1)

### Line #: 
GTMSessionFetcher.m : 987

**Comment by thomasvl** [comment]
I'm not sure what' you are trying to report, as long as `GTM_ALLOW_INSECURE_REQUESTS` isn't defined the code right above what you reference [should already be doing that](https://github.com/google/gtm-session-fetcher/blob/main/Sources/Core/GTMSessionFetcher.m#L964-L974).
