### ISSUE TITLE
Critical Severity Risk - Privacy Violation

### ISSUE THREAD

**Issue by arunkumar-g3690** [google/gtm-session-fetcher#350]
### Summary
The function beginFetchMayDelay:mayAuthorize:mayDecorate:() in GTMSessionFetcher.m mishandles confidential information on line 809. The program could compromise user privacy.The identified function mishandles confidential information. This program could compromise user privacy.

### Explanation
Privacy violations occur when:

1. Private user information enters the program.

In this case, the data comes from in GIDSignIn.m on line 411.

2. The data is written to an external location, such as the console, file system, or network.

In this case, the data is passed to uploadTaskWithStreamedRequest:() in GTMSessionFetcher.m on line 809.

Example 1: The following code retrieves geolocation information from the mobile device and sends it to a server, while logging it to the device. Although many developers trust the log files as a safe storage location for any and all data, it should not be trusted implicitly, particularly when privacy is a concern.

> locationManager = [[CLLocationManager alloc] init];
locationManager.delegate = self;
locationManager.desiredAccuracy = kCLLocationAccuracyBest;
locationManager.distanceFilter = kCLDistanceFilterNone;
[locationManager startUpdatingLocation];
CLLocation *location = [locationManager location];
// Configure the new event with information from the location
CLLocationCoordinate2D coordinate = [location coordinate];

>NSString *latitude = [NSString stringWithFormat:@"%f", coordinate.latitude];
NSString *longitude = [NSString stringWithFormat:@"%f", coordinate.longitude];

>NSLog(@"dLatitude : %@", latitude);
NSLog(@"dLongitude : %@",longitude);

>NSString *urlWithParams = [NSString stringWithFormat:TOKEN_URL, latitude, longitude];

>NSMutableURLRequest *request = [NSMutableURLRequest requestWithURL:[NSURL URLWithString:urlWithParams]];
[request setHTTPMethod:@"GET"];
[[NSURLConnection alloc] initWithRequest:request delegate:self];

### Recommendation
When security and privacy demands clash, privacy should usually be given the higher priority. To accomplish this and still maintain required security information, cleanse any private information before it exits the program.

To enforce good privacy management, develop and strictly adhere to internal privacy guidelines. The guidelines should specifically describe how an application should handle private data. If your organization is regulated by federal or state law, ensure that your privacy guidelines are sufficiently strenuous to meet the legal requirements. Even if your organization is not regulated, you must protect private information or risk losing customer confidence.

The best policy with respect to private data is to minimize its exposure. Applications, processes, and employees should not be granted access to any private data unless the access is required for the tasks that they are to perform. Just as the principle of least privilege dictates that no operation should be performed with more than the necessary privileges, access to private data should be restricted to the smallest possible group.

### Which Version of framework is used?
GoogleSignIn-iOS (7.0.0) uses GTMSessionFetcher (< 4.0, >= 1.1)

Line #: Similar security threat was spotted on multiple files & in multiple lines within the SDK mentioned below
GTMSessionFetcher​.m:809
GTMSessionFetcher​.m:818
GTMSessionFetcher​.m:804
GTMSessionFetcher​.m:627
GTMSessionFetcher​.m:573
GTMSessionFetcher​.m:799
GTMSessionFetcher​.m:816
GTMSessionFetcher​.m:810
GTMSessionFetcher​.m:805
GTMSessionFetcher​.m:627
GTMSessionFetcher​.m:800
GTMSessionFetcher​.m:824
GTMSessionFetcher​.m:539
GTMSessionFetcher​.m:814
GTMSessionFetcher​.m:621
GTMSessionFetcher​.m:826
GTMSessionFetcherService​ .m:457
GTMSessionFetcherService​ .m:449
GTMSessionFetcherService​ .m:456
GTMSessionFetcherService​ .m:391
GTMSessionFetcherService​ .m:380
GTMSessionFetcherService​ .m:463

**Comment by thomasvl** [comment]
The library allows `GTMSESSION_ASSERT_DEBUG_OR_LOG` to be overridden with a custom definition to completely suppress all behaviors.  It is also only used in cases that are more likely programmer errors vs just fetch failure (but it wouldn't hurt to re-validate that).  But the private data you mention is also only ends up in the device logs, which your example code is also explicitly doing itself. 😄
