### ISSUE TITLE
High Severity Risk - Insecure Storage: HTTP Response Cache Leak

### ISSUE THREAD

**Issue by arunkumar-g3690** [google/gtm-session-fetcher#351]
### Summary
On line 987 of GTMSessionFetcher.m, the method createSessionWithDelegate:sessionIdentifier:() performs a URL request without configuring the URL loading system to prevent the caching of HTTP(S) responses.The identified method performs a URL request without configuring the URL loading system to prevent the caching of HTTP(S) responses.

### Explanation
The HTTP(S) responses may contain sensitive data such as session cookies and API tokens. The URL loading system will cache all the HTTP(S) responses for performance reasons, storing them unencrypted in the {app ID}/Library/Caches/com.mycompany.myapp/Cache.db* files.

### Recommendation
In order to prevent the caching of HTTP(S) responses, implement the NSURLSessionDataDelegate URLSession:dataTask:willCacheResponse:completionHandler: delegate method and call completionHandler(nil) when the response should not be cached.

Example: The following implementation of the NSURLSessionDataDelegate URLSession:dataTask:willCacheResponse:completionHandler: delegate method completely disables HTTP(S) response caching by always returning nil:

`- (void)URLSession:(NSURLSession *)session dataTask:(NSURLSessionDataTask *)dataTask willCacheResponse:(NSCachedURLResponse *)proposedResponse completionHandler:(void (^)(NSCachedURLResponse * __nullable ))completionHandler {
completionHandler(nil);
}`

### Which Version of framework is used?
GoogleSignIn-iOS (7.0.0) uses GTMSessionFetcher (< 4.0, >= 1.1)

### Line #:
GTMSessionFetcher.m : 987

**Comment by thomasvl** [comment]
This should already be under developer control for what they want, the [header outlines how to configure it](https://github.com/google/gtm-session-fetcher/blob/main/Sources/Core/Public/GTMSessionFetcher/GTMSessionFetcher.h#L142-L156).
