### ISSUE TITLE
iOS 17 New required reason API

### ISSUE THREAD

**Issue by lakshmankreditbee** [google/gtm-session-fetcher#360]
From Apple's newly published document ["Describing use of required reason API"](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api):

> Your app or third-party SDK must declare one or more approved reasons that accurately reflect your use of each of these APIs and the data derived from their use. You may use these APIs and the data derived from their use for the declared reasons only. These declared reasons must be consistent with your app’s functionality as presented to users, and you may not use the APIs or derived data for tracking.

Will gtm-session-fetcher sdk be either removing the use of these APIs or providing a privacy manifest file for the iOS SDK? Or perhaps are you in contact with Apple about this issue?

**Comment by thomasvl** [comment]
Thanks for the issue. We are tracking this internally and will address it a little later this year.

**Comment by nabs-m** [comment]
Hey @thomasvl, is this still planned for this year?

**Comment by thomasvl** [comment]
We're working on this internally, not sure it will make the end of the year.

I think I see a path for making this work with CocoaPods (so it gets picked up as a resource correctly for Xcode), but I can't find anything in Apple's docs about how to do this properly with SwiftPM.  If anyone has pointers for how to do this correctly for Xcode+SwiftPM integration, it would be much appreciated.

**Comment by nabs-m** [comment]
Thanks for the update @thomasvl. I also don't know how to do this for SwiftPM, but if it helps you confirm things for CocoaPods, I was working on enabling the same thing in another library earlier. I believe you'd just need to add the following in the `.podspec` (under the appropriate subspec of course):

`sp.resource_bundle = {'Framework name' => ['Path/to/PrivacyInfo.xcprivacy']}`

I didn't get the chance to test it yet, but it's based off [this](https://github.com/CocoaPods/CocoaPods/issues/10325#issuecomment-1718723762).

**Comment by thomasvl** [comment]
Thanks, yup, that's basically what I was looking at for CocoaPods.

**Comment by lcodetechgitrep** [comment]
> We're working on this internally, not sure it will make the end of the year.
> 
> I think I see a path for making this work with CocoaPods (so it gets picked up as a resource correctly for Xcode), but I can't find anything in Apple's docs about how to do this properly with SwiftPM. If anyone has pointers for how to do this correctly for Xcode+SwiftPM integration, it would be much appreciated.


FMDB has added it via SPM (2.7.8 version)

**Comment by nabs-m** [comment]
@thomasvl Does this maybe help for SPM? https://github.com/airbnb/lottie-ios/pull/2252/files#diff-f913940c58e8744a2af1c68b909bb6383e49007e6c5a12fb03104a9006ae677eR22

**Comment by thomasvl** [comment]
> @thomasvl Does this maybe help for SPM? https://github.com/airbnb/lottie-ios/pull/2252/files#diff-f913940c58e8744a2af1c68b909bb6383e49007e6c5a12fb03104a9006ae677eR22

Thanks, looks like it might.

**Comment by lakshmankreditbee** [comment]
Hi, when can we expect an update regarding this issue?

**Comment by thomasvl** [comment]
Working on it, but no specific ETA, some things with Google being worked through.
