### ISSUE TITLE
ios17 incompatibility with Pod (flutter)

### ISSUE THREAD

**Issue by ozgunozerk** [google/gtm-session-fetcher#362]
I have a flutter project, it was working well. 
After I upgraded xcode, it stopped working. Compilation is failing, with this error:

```
Launching lib/main.dart on iPhone 15 Pro Max in debug mode...
Running pod install...
Running Xcode build...
Xcode build done.                                           10.5s
Failed to build iOS app
Semantic Issue (Xcode): Property with 'retain (or strong)' attribute must be of object type
/Users/ozgunozerk/Developer/StudioProjects/howmuch/ios/Pods/GTMSessionFetcher/Sources/Core/Public/GTMSessionFetcher/GTMSessionFetcher.h:618:0

Semantic Issue (Xcode): Property with 'retain (or strong)' attribute must be of object type
/Users/ozgunozerk/Developer/StudioProjects/howmuch/ios/Pods/GTMSessionFetcher/Sources/Core/Public/GTMSessionFetcher/GTMSessionFetcher.h:1158:0

Could not build the application for the simulator.
Error launching application on iPhone 15 Pro Max.
```

I'm on Mac M1 if this helps.

I have updated all my dependencies, and rebuilt pod files. I don't know what the issue is here.

However, I noticed that version 2.3.0 is in use, due to google-sign-in package's most up to date version requires GTMSessionFetcher's version to be less than 3.0.0.

It is pretty annoying, since this is a blocking issue, and I cannot make progress on my mobile application.

**Comment by thomasvl** [comment]
Looking at [google-sign-in](https://github.com/google/GoogleSignIn-iOS/blob/main/GoogleSignIn.podspec), it seems like they support the 3.x version of the SessionFetcher, so it sounds like the issue if some package in your dependency graph limiting things and not a problem with this package specifically.  I'd suggest looking at your dependency graph and see if you can update things there or if there is something preventing updates opening issues with those specific dependencies.

**Comment by ozgunozerk** [comment]
Couple of things:
1. everything is up to date on my end, and when I removed google-sign-in, flutter was able to bump the `GtmSessionFetcher` to version 3.x.x (my other dependency that was dependent on GtmSessionFetcher is Firebase)
2. bumping `GtmSessionFetcher` to 3.x.x also did not solve the problem. I'm still getting the error I described above
3. when I get rid of `GtmSessionFetcher` by removing both `google-sign-in` and `firebase` packages, the error was gone and I was able to build the application on iOS 17 with silicon architecture (intel chips do seem fine)
4. even with `GtmSessionFetcher`, I'm able to build on android, so this issue is only relevant with iOS17 and XCode 15 and Sonoma
5. here is another issue I opened at flutter repo: https://github.com/flutter/flutter/issues/137137#issuecomment-1778560522
6. I've created a new project from scratch, used the example from official google-sign-in repo: https://github.com/flutter/packages/tree/main/packages/google_sign_in/google_sign_in/example.

Cocoapods, flutter sdk, android studio, everything is up to date. Yet, I'm getting the same error message.


I don't think this issue should be closed, the problem is not solved. And the problem does not arise from my code as I explained. It could be my configuration, but I give this a very slight chance, since I've updated everything to their latest version.

**Comment by paulb777** [comment]
You need GoogleSignIn 7.x to get the updated GTMSessionFetcher 3.x dependency

**Comment by ozgunozerk** [comment]
@paulb777 , I know, but on official pub.dev: https://pub.dev/packages/google_sign_in -> the most up to date version is 6.1.5

Nevertheless, this is becoming orthogonal to the original issue, as I explained as the 2nd bullet point on my previous post:
> 2. bumping GtmSessionFetcher to 3.x.x also did not solve the problem. I'm still getting the error I described above

**Comment by thomasvl** [comment]
Thanks for the update. Apologies, the original issue did read as the problem was from using the older version; and not a new issue (I think I've fixed this same sorta issue before, but maybe it was another project).

**Comment by thomasvl** [comment]
What are your repo steps?  Just `main` and opening the Package.swift in Xcode 1.5.0.1, I'm not able to get any warning like this building or running the analyzer.  I'd sorta like to repo this so I can figure see if I can set something up on CI to catch these going forward.

**Comment by ozgunozerk** [comment]
Hmm... Is your machine M1 ?

I'm just opening the repo as a project with Android Studio Giraffe, and then I start the simulator (iOS 17 - iPhone 14), and then I hit the run button, then I get the error I posted in the very beginning

**Comment by thomasvl** [comment]
Nope, I'm on Intel.  Can you repo things without Android studio in the mix, or isolate what the raw commands are under the hood so we can better understand what's triggering this?

**Comment by ozgunozerk** [comment]
In the other issue I've opened, another person tried to replicate it but failed to do so, he was also using intel chipset. I think this might be related to M1 (and possibly other apple silicon).
Sure! I'll try my best but I'm quite alien to iOS and macOS development.

**Comment by ozgunozerk** [comment]
Ok, clone the repo, go to the repo's directory in terminal, and then run `flutter run` (while simulator is open)

**Comment by thomasvl** [comment]
> Ok, clone the repo, go to the repo's directory in terminal, and then run `flutter run` (while simulator is open)

Doesn't repo on an Intel based Mac, so this is sounds like something odd with flutter and building for Apple Silicone.

Looking at [Apple's dispatch headers](https://github.com/apple-oss-distributions/libdispatch/blob/e8b6b45992bdeb06e094571fc2b9c0646780a41b/os/object.h#L50), I'm wondering if Flutter some how has things oddly configured in some context that that's what trips things up, as that really shouldn't be use any more.

**Comment by thomasvl** [comment]
Had someone here try on a M2 based machine, and no issue with `flutter run` on the examples either.  So this is sounding more specific to your machine/setup.

**Comment by ozgunozerk** [comment]
> Had someone here try on a M2 based machine, and no issue with flutter run on the examples either. So this is sounding more specific to your machine/setup.

Hmm, when was that? 

My setup was working great for 2.5 years, it just got broke after Sonoma update (with XCode 15 and iOS 17). 
I'd really like to know if he can successfully run this (https://github.com/ozgunozerk/test-gtm-ios): this is google-sign-in example extracted into a separate repo, I haven't touched the code at all, yet I'm unable to run it with the same error.

**Comment by thomasvl** [comment]
> > Had someone here try on a M2 based machine, and no issue with flutter run on the examples either. So this is sounding more specific to your machine/setup.
> 
> Hmm, when was that?

Shortly before I posted the comment.

> My setup was working great for 2.5 years, it just got broke after Sonoma update (with XCode 15 and iOS 17). I'd really like to know if he can successfully run this (https://github.com/ozgunozerk/test-gtm-ios): this is google-sign-in example extracted into a separate repo, I haven't touched the code at all, yet I'm unable to run it, getting the same error.

Just to be clear:
1. Clone it.
2. `cd` into the directory
3. `flutter run`
Those steps?

**Comment by ozgunozerk** [comment]
Yes, those steps indeed

**Comment by thomasvl** [comment]
Working here: Xcode 15.1 iOS 17 device, from both an M1 and M2.

Since you mentioned an OS update when it started to fail, that could be related, try: `env | sort` and maybe try `flutter run --verbose` to get more details about your setup?

**Comment by ozgunozerk** [comment]
thank you very much for the support. 

Here is `env | sort`:
```
❯ env | sort                                                                                   
AR=/opt/homebrew/opt/llvm@15/bin/llvm-ar
CARGO_TARGET_DIR=/Users/ozgunozerk/.cargo-target
CC=/opt/homebrew/opt/llvm@15/bin/clang
COMMAND_MODE=unix2003
HOME=/Users/ozgunozerk
HOMEBREW_CELLAR=/opt/homebrew/Cellar
HOMEBREW_PREFIX=/opt/homebrew
HOMEBREW_REPOSITORY=/opt/homebrew
INFOPATH=/opt/homebrew/share/info:
LC_CTYPE=en_US.UTF-8
LESS=-R
LOGIN_SHELL=1
LOGNAME=ozgunozerk
LSCOLORS=Gxfxcxdxbxegedabagacad
MANPATH=/Users/ozgunozerk/.nvm/versions/node/v20.2.0/share/man:/opt/homebrew/share/man::
NVM_BIN=/Users/ozgunozerk/.nvm/versions/node/v20.2.0/bin
NVM_CD_FLAGS=-q
NVM_DIR=/Users/ozgunozerk/.nvm
OLDPWD=/Users/ozgunozerk/Developer/StudioProjects/howmuch
PAGER=less
PATH=/opt/homebrew/opt/llvm/bin:/Users/ozgunozerk/.nvm/versions/node/v20.2.0/bin:/Users/ozgunozerk/.local/bin:/Users/ozgunozerk/.gem/ruby/X.X.0/bin:/Users/ozgunozerk/.local/share/gem/ruby/3.0.0/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/ozgunozerk/.cargo/bin:/Users/ozgunozerk/Library/Application Support/JetBrains/Toolbox/scripts:/Users/ozgunozerk/Developer/flutter/bin:/Users/ozgunozerk/.pub-cache/bin
PWD=/Users/ozgunozerk/Developer/StudioProjects/howmuch
SHELL=/bin/zsh
SHLVL=1
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.51vk5Bbwok/Listeners
STARSHIP_SESSION_KEY=2029318140182592
STARSHIP_SHELL=zsh
TERM=xterm-256color
TERMINAL_EMULATOR=JetBrains-JediTerm
TERM_SESSION_ID=7ae09458-dbaf-4820-bdc8-46b9a3be5070
TMPDIR=/var/folders/my/22_qs9hj3rn6g3w85r4rjdh40000gn/T/
USER=ozgunozerk
XPC_FLAGS=0x0
XPC_SERVICE_NAME=0
ZSH=/Users/ozgunozerk/.oh-my-zsh
_=/usr/bin/env
__CFBundleIdentifier=com.google.android.studio
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
__INTELLIJ_COMMAND_HISTFILE__=/Users/ozgunozerk/Library/Caches/Google/AndroidStudio2022.2/terminal/history/howmuch-history1
```

`flutter run --verbose` output is too long, so I'm sharing a txt file link instead: https://jmp.sh/s/NWwkvmvXUBgeVqdIqJqd

updated XCode to 15.1 from 15.0, ran `brew upgrade`, then ran `flutter clean`, still getting the same error :/
very frustrating :D

**Comment by ozgunozerk** [comment]
Done! It was due to llvm version checked out to 15. Probably after sonoma and xcode 15, they broke compatibility with llvm 15, and that was the reason. It's working now. Thank you all for your efforts on this, appreciated 🙏
