### ISSUE TITLE
Warning - Signing requires a development team

### ISSUE THREAD

**Issue by CatchABus** [google/gtm-session-fetcher#375]
When trying to build my app in Xcode, I receive `Signing for "GTMSessionFetcher-GTMSessionFetcher_Core_Privacy" requires a development team.` warning.
I use version 3.3.0.

**Comment by thomasvl** [comment]
I'm guessing you are integrating via CocoaPods?

I believe that's going to be something on your project side of things.

@ncooke3 @paulb777 - ideas?

**Comment by thomasvl** [comment]
@CatchABus can you share a little more about your setup?  what's your podfile look like?  Are you using frameworks?  etc.

**Comment by thomasvl** [comment]
And for completeness:
- Are you building for iOS or some other platform?
- What version of Xcode are you using?

**Comment by paulb777** [comment]
And what version of CocoaPods?

**Comment by CatchABus** [comment]
Thank you very much for your quick responses. I include all details below.

- Build for iOS
- Cocoapods 1.11.3
- Usage of frameworks
- Xcode 14.2

**Comment by paulb777** [comment]
You may be running into https://github.com/CocoaPods/CocoaPods/issues/11402 that was fixed in CocoaPods 1.12.0

**Comment by thomasvl** [comment]
@CatchABus if the CocoaPods update works for you, I'll update our cocoapods min version requirement and do a new release to help others avoid this.

**Comment by CatchABus** [comment]
> @CatchABus if the CocoaPods update works for you, I'll update our cocoapods min version requirement and do a new release to help others avoid this.

It's exactly as @paulb777 said. Updating to latest cocoapods version fixed my problem.
Thank you so much!

**Comment by thomasvl** [comment]
@CatchABus thanks for letting us know, I'll go ahead and update the podspec to have the requirement and do a new release to hopefully help other folks avoid this.
