### ISSUE TITLE
GTMSessionFetcher cannot be integrated as static libraries with CocoaPods because it does not define a module (`DEFINES_MODULE`)

### ISSUE THREAD

**Issue by jmagman** [google/gtm-session-fetcher#384]
**Steps to reproduce**
1. [Install CocoaPods.](https://guides.cocoapods.org/using/getting-started.html#installation)
2.  In Xcode, make new iOS app project. 
2. cd into the directory and `pod init` to initialize CocoaPods.
3. In the generated `Podfile` comment out `use_frameworks!` to embed as static libs.  Add a pod that depends on `GTMSessionFetcher`, for example, `GTMAppAuth`:
```ruby
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!
  pod 'GTMAppAuth', '4.1.1'
```
5. Run `pod install`

**Result**
`pod install` fails:
```
$ pod install
Analyzing dependencies
Downloading dependencies
Installing AppAuth (1.7.3)
Installing GTMAppAuth (4.1.1)
Installing GTMSessionFetcher (3.3.2)
[!] The following Swift pods cannot yet be integrated as static libraries:

The Swift pod `GTMAppAuth` depends upon `GTMSessionFetcher` and `AppAuth`, which do not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.
```

`GTMSessionFetcher` is not setting up a module, and doesn't have `DEFINES_MODULE` for that to be done automatically.

This can be fixed by adding `DEFINES_MODULE` to [GTMSessionFetcher.podspec](https://github.com/google/gtm-session-fetcher/blob/main/GTMSessionFetcher.podspec).  See [CocoaPods documentation about modular headers](https://blog.cocoapods.org/CocoaPods-1.5.0/#modular-headers).
```ruby
  s.xcconfig = {
     'DEFINES_MODULE' => 'YES',
  }
```

**Comment by thomasvl** [comment]
@paulb777 - doesn't seem like you all have to do this for Firebase?  This sorta feels like a "down stream" need that shouldn't be pushed into the `.podspec` here.  Anyway, thoughts?

**Comment by paulb777** [comment]
Because of the transition to Swift implementations beginning in Firebase 9.0, Firebase now requires `use_frameworks!` or `use_frameworks! :linkage => :static` in Podfiles.

**Comment by paulb777** [comment]
Without testing, I would guess so, since modules should always be built for frameworks.  cc: @mdmathias
