### ISSUE TITLE
GTMSessionFetcher v3.4.0: Cocoapods warning becase new `"xcconfig": { "DEFINES_MODULE": "YES" }` on podspec file

### ISSUE THREAD

**Issue by pmanuelli** [google/gtm-session-fetcher#389]
Hello,

We integrate GTMSessionFetcher using cocoapods. After upgrading GTMSessionFetcher to version 3.4.0 (via updating GoogleSignIn to version 7.1.0) we are getting the following warning:

```
[!] The `MyTarget` target overrides the `DEFINES_MODULE` build setting defined in `Pods/Target Support Files/Pods-base-MyProjectBase-MyProject/Pods-base-MyProjectBase-MyProject.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
```

Is this change intended? Maybe you wanted to use `pod_target_xcconfig` instead of `xcconfig` on the podspec file?

Thank you!

**Comment by thomasvl** [comment]
The change was done to fix #384

I'm not enough of a cocoapods expert to fully know what's going wrong here, but were you by chance forcing the value of `DEFINES_MODULE` before and it's complaining about your override vs. what the podspec is now doing?

@paulb777 @mdmathias @jmagman any ideas?

**Comment by thomasvl** [comment]
Rereading some docs, I'm thinking the original issue suggested fix was wrong and it should be `pod_target_xcconfig` not `xcconfig`.

**Comment by paulb777** [comment]
Agreed. Just read the same thing.

**Comment by jmagman** [comment]
Apologies for suggesting the wrong fix, I hadn't seen that warning before.
