### ISSUE TITLE
sharedApplication is unavailable, not available on iOS (app extension).

### ISSUE THREAD

**Issue by ashokds** [google/gtm-session-fetcher#54]
Hello!

Our project is using Cocoapods 1.0.1 and following are part of the podspec.
    pod 'GoogleAPIClient/Drive'
    pod 'GTMOAuth2'
    pod 'GTMSessionFetcher'

Which installs:

Using GTMOAuth2 (1.1.1)
Using GTMSessionFetcher (1.1.4)
Installing GoogleAPIClient 1.0.4 (was 1.0.3)

Upon build it ends in following error:

.../Pods/GTMSessionFetcher/Source/GTMSessionFetcher.m:1917:56: 'sharedApplication' is unavailable: not available on iOS (App Extension) - Use view controller based solutions where appropriate instead.

.../Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIApplication.h:105:1: 'sharedApplication' has been explicitly marked unavailable here

File: GTMSessionFetcher.m

`Line (1914 - 1920):`
`// Some projects use GTM_BACKGROUND_TASK_FETCHING to avoid compile-time references`
`// to UIApplication.`
`#if GTM_BACKGROUND_TASK_FETCHING`
`return (id<GTMUIApplicationProtocol>) [UIApplication sharedApplication];`
`#else`
`return nil;`
`#endif`

**Comment by thomasvl** [comment]
Just like the text you quoted, you'll want to define `GTM_BACKGROUND_TASK_FETCHING=0` for your build.

**Comment by thomasvl** [comment]
btw - I've tried to find a way to auto detect when the Xcode setting is enabled and auto enable the flag, but I haven't found a way yet.

**Comment by ashokds** [comment]
Thanks @thomasvl, I'll add it to build settings. There is similar issue with shareAppliation being used with other libraries (AFNetworking, epthread) as well. 
https://github.com/ephread/Instructions/issues/21
https://github.com/AFNetworking/AFNetworking/issues/2119

Could you please point me to the side-effects of not enabling background task fetching?

**Comment by ashokds** [comment]
Hi @thomasvl 

I have been dealing with other tasks at hand, sorry about posting a late reply. Adding a preprocessor task to declare "GTM_BACKGROUND_TASK_FETCHING=0" worked. 

Thanks,
Ashok

**Comment by georgek1991** [comment]
where to declare GTM_BACKGROUND_TASK_FETCHING=0. can somebody point out.

**Comment by thomasvl** [comment]
@georgek1991 in Xcode's _Preprocessor Macros_ section.

**Comment by georgek1991** [comment]
@thomasvl can you please tell the steps.

**Comment by georgek1991** [comment]
I added the GTM_BACKGROUND_TASK_FETCHING=0 in Preprocessor Macros for both release and debug. But I am still getting the error. Am I missing something. I Added updated pod file for my extension.

**Comment by paulofierro** [comment]
I have the same issue as @georgek1991. Setting that value in the Preprocessor Macros doesn't appear to do anything.

**Comment by jonblatho** [comment]
@georgek1991 @paulofierro Did either of you ever find a fix?

**Comment by jonblatho** [comment]
Alright, found the fix myself by combining information from [this pull request](https://github.com/google/gtm-session-fetcher/pull/70) and [this comment](https://github.com/google/google-api-objectivec-client/issues/159#issuecomment-195215433)...

In your Podfile, add the following lines:

    post_install do |installer|
      installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = '$(inherited) GTM_BACKGROUND_UIAPPLICATION=0'
        end
      end
    end

The preprocessing flag changed from `GTM_BACKGROUND_TASK_FETCHING` to `GTM_BACKGROUND_UIAPPLICATION` with that pull request, so I figured I'd update here with a comment.

cc @paulofierro, if you didn’t find this already

**Comment by thomasvl** [comment]
#74 includes a change that should make this a lot easy to deal with.  There is still a directive to compile out the support, but things should work without having to do that.

We'll look at doing a CocoaPods bump also for this.

**Comment by thomasvl** [comment]
1.1.9 pod pushed, so this should not need a define any more.
