### ISSUE TITLE
httpAuth test failures

### ISSUE THREAD

**Issue by thomasvl** [google/gtm-session-fetcher#67]
-[GTMSessionFetcherFetchingTest testHTTPAuthentication]
 -[GTMSessionFetcherFetchingTest testHTTPAuthentication_WithoutFetcherService]

https://travis-ci.org/google/gtm-session-fetcher/jobs/163821313

**Comment by thomasvl** [comment]
They are Digest Authentication failures.

**Comment by Cheecherngho799** [comment]
Lol ok cool.
