### ISSUE TITLE
-[GTMSessionFetcherCookieTest  testCookieStorage] failing with Xcode 8.3

### ISSUE THREAD

**Issue by thomasvl** [google/gtm-session-fetcher#79]
It seems to be failing for all OSes, and appears to be because neither of the expire flags wants to work any more.

**Comment by mwyman** [comment]
It looks to me like the behavior of NSHTTPCookie changed at some point, but I'd need to check exactly where it happened. Basically, if you pass in _any_ value for NSHTTPCookieDiscard, it treats it as YES and will disregard any max-age or expiration date. If you do _not_ set NSHTTPCookieDiscard but provide a max-age, it appropriately provides an expiration date and the tests pass.
