### ISSUE TITLE
UnitTest Flake / Timing issues

### ISSUE THREAD

**Issue by thomasvl** [google/gtm-session-fetcher#80]
Running the tests with Xcode 8.3 almost always passes, but under automation (travis or otherwise), we see a lot of flakes.  If the automation uses VMs (travis), it seems like they are even more common.  So odds are we've got timing issues within the tests.

**Comment by Cheecherngho799** [comment]
Automation of flakes

**Comment by Cheecherngho799** [comment]
Jailed

**Comment by thomasvl** [comment]
#182 helps with this.

**Comment by thomasvl** [comment]
Hopefully fixed with #183.
