### ISSUE TITLE
Xcode 9 beta 1 curious error for [[self alloc] initWithDelegate]

### ISSUE THREAD

**Issue by sergiocampama** [google/gtm-session-fetcher#87]
GTMHTTPServer.m fails to compile with the following error:

"Multiple methods named 'initWithDelegate'."

It looks like the live issues processor can't deduce the correct class to use for self. Will wait for future versions of Xcode beta to see if it's fixed before filing a radar.

**Comment by thomasvl** [comment]
fyi - last time I saw something like this it was because things weren't strongly typed where the init was happening.  We might be able to tweak things so they are better typed to avoid it.
