### ISSUE TITLE
Delegate Callback Queue not configured for restored background upload sessions

### ISSUE THREAD

**Issue by jablair** [google/gtm-session-fetcher#92]
If you create an upload fetcher with the `useBackgroundSession` property set to `YES` and then resume the app while the upload is still in progress, the reconstructed fetcher does not send messages to its configured `sendProgressBlock`.

It looks the like the issue is that the reconstruction process doesn't configure the `_delegateCallbackQueue` property of the fetcher (whereas creating a new fetcher configures it to `self.callbackQueue` in `-[GTMSessionFetcher beginFetchWithCompletionHandler:]`).

I'm not sure if this is a bug or an issue that I'm not fully understanding. Configuring the delegate queue in `+[GTMSessionUploadFetcher uploadFetchersForBackgroundSessions]` starts propagating the calls to `sendProgressBlock` - around https://github.com/google/gtm-session-fetcher/blob/master/Source/GTMSessionUploadFetcher.m#L301, add

```
[uploadFetcher setDelegateCallbackQueue: uploadFetcher.callbackQueue];
```

**Comment by mwyman** [comment]
I don't see a reason why the delegateCallbackQueue shouldn't be set. It seems like an oversight.

I think it might be cleaner to set the delegateCallbackQueue when creating the fetcher in [uploadFetcherForSessionIdentifierMetadata:](https://github.com/google/gtm-session-fetcher/blob/master/Source/GTMSessionUploadFetcher.m#L220).

**Comment by jablair** [comment]
Thanks @mwyman - I had about 2 days experience with the API when I stumbled across this, so I'm not surprised there's a better place to address it.
